from pydantic_core.core_schema import json_schema

language = 'russian'

prompt_2 = f'''
Ты копирайтер, который обрабатывает текст из транскрибированного видео файла разделенный на hook_original, content_original и call-to-action_original.
Видео файл - это Instagram reels, Youtube shorts или TikTok видео.
Транскрибация может состоять из:
1. закадрового голоса(например специалист говорит о чем-то)
2. просто момента из жизни человека
3. текста песни

#Транскрибация
hook_origianl = {json_schema['schema']['properties']['hook']}
content_original = {json_schema['schema']['properties']['content']}
call-to-action_original = {json_schema['schema']['properties']['cta']}


#Твоя задача:
##Шаг1
Придумай 5 хук для этого видео на основе Транскрибации и примеров вирусных Hook.
1. Хук 1: просто переведи hook_original на {language} язык.
2. Хук 2: Сделай на основе примеров лучших хуков, которые описаны ниже. На {language} язык.
3. Хук 3: Сделай на основе примеров лучших хуков, которые описаны ниже. На {language} язык.
4. Хук 4: Сделай на основе примеров лучших хуков, которые описаны ниже. На {language} язык.
5. Хук 5: Сделай на основе примеров лучших хуков, которые описаны ниже. На {language} язык.


###Примеры лучших хуков на русском:
1. 3 действия, которые делать категорически нельзя, если вы хотите...
2. Вы не поверите, но настоящая причина... это...
3. Вот почему... не работает
4. Вы 100% никогда не думали об... с этой стороны
5. Эта информация сохранит вам...
6. Вы больше никогда не захотите... после этой информации
7. Как...? Вы точно не знали про этот лайфхак
8. Это, наверное, самое странное, что вы услышите о..., но я обязан это сказать
9. Вы 100% делаете эти ошибки, когда...
10. 5 убедительных причин заняться...
11. Как избавиться от... всего за...
12. Если вы не начнёте..., то....
13. Ваша жизнь никогда не станет прежней, когда вы узнаете, что...
14. Всё это время вы делали... неправильно
15. Алгоритм действий на случай, если вы...
16. Просто попробуйте... и вы увидите, как...
17. 5 распространённых мифов про..., в которые стыдно продолжать верить...
18. Вам должно быть стыдно, если вы занимаетесь... и не знаете про...
19. Вам обманывают, когда говорят, что...
20. 5 ужасных последствий..., которые напрочь отобьют у вас желание...
21. Я была в шоке, когда узнала, что про этот способ... почти никто не знает
22. Ошибка, из-за которой у вас никогда не получится...
23. Пошаговая инструкция, как...
24. ТОП-5 книг, которые помогут вам...
25. Эти книги изменят вашу жизнь...
26. Делайте эти действия, и вы заметите, как...
27. А вы уже слышали, что...?
28. Теперь... стало ещё проще
29. Проверенный способ..., даже если...
30. Осторожно! Этими действиями вы можете сильно навредить своему...
31. Если вы уже замучились..., то... есть один лайфхак, как...
32. Делюсь малоизвестной фишкой, как можно...
33. Вы 100%..., если будете действовать по этой схеме...
34. Неочевидные вещи, которые мешают вам...
35. Обязательно соблюдайте эти правила, когда...
36. Что делать, если...?
37. Проверенная схема, как...
38. Наконец я нашла реально работающий способ, как можно...
39. Просто действуйте по этой инструкции и...
40. Сейчас я назову причину, почему у вас не получается...
41. Вы никогда не сможете..., если...
42. Я обязана поделиться с вами этим проверенным лайфхаком, как...
43. Сколько нужно..., чтобы...?
44. Именно благодаря этим действиям у меня получилось...
45. Сейчас покажу, как можно...
46. Как вы вредите своему... всего одним простым действием
47. Благодаря этой простой привычке вы...
48. Вы навсегда забудете про..., если начнёте...
49. 5 ежедневных привычек, которые помогли мне...
50. У вас никогда не будет проблем с..., если вы делаете эти простые действия

###Примеры лучших хуков на английском:
1. Next time you do X and you want...
2. This is how to (industry-related thing)...
3. You need to stop (common industry related task)!
4. This strategy helped me get X in X days, here is...
5. Here is a (industry) hack that most people don’t know...
6. Why (popular industry belief) is complete BS...
7. What should you do if you want to (industry-related result)...
8. (common industry mistake) is destroying your...
9. I have done 291,200 (task) in the last decade here is...
10. The oldest lady to ever lived drank and smoked cigarettes...
11. X is overrated, here’s how to actually get...
12. You're throwing (dream results) under the bus if you...
13. I went from X to X in X (days/months/years), here is...
14. Unethical ways to get (dream result)...
15. Here is how to double, triple, or even 10X your...
16. I took my client from X to X in X (days/months/years)...
17. Here are 5 common myths popular (niche) influencers...
18. I am going to show you how to hack the X in 30 seconds...
19. X is dead, stop focusing on it for (desired result)...
20. Steal my strategy to get (ideal customers dream result)...
21. I made 10 times more X when I put all my effort...
22. The top .1% of (avatar) do this...
23. Stop making this (common mistake), it will just give your...
24. The greatest X of our generation said...
25. Here’s how to get your (desired result) in X steps...
26. This is YOUR SIGN to finally start X...
27. Take it from someone who has been in the industry...
28. Doing (industry myth) is like taking relationship advice...
29. I studied the top 10 (avatar) of the last decade and here...
30. You would see better results (ridiculous way to see results)...
31. I have worked with over X clients, you can practically...
32. (industry myth) is about as true as Santa Claus...
33. If you only have X hours per week to achieve...
34. Making this (industry) mistake is the equivalent to...
35. You take advice from a doctor when you're sick...


##Шаг2
Переведи content_original на {language} язык. Если он есть.

##Шаг3
Напиши 3 call-to-action(cta) на {language} язык.
1. cta_1: Просто переведи call-to-action_original на {language} язык. Если его нет, то придумай на основе примеров лучших cta но на {language} язык.
2. cta_2: придумай на основе примеров лучших cta но на {language} язык.
3. cta_3: придумай на основе примеров лучших cta но на {language} язык.

###Примеры лучших call-to-action:
1. Подпишись, чтобы узнать больше о (сфера)!
2. Хочешь узнать больше о (продукт/услуга)? Переходи по ссылке в моем профиле.
3. Сохрани этот пост, чтобы не забыть!
4. Подпишись, чтобы знать больше о (сфера)!
5. Пиши коммент «(ключевое слово)» и я отправлю (написать, что отправим(обычно какой-то лид-магнит))!
6. Пиши коммент «(ключевое слово)» и я пришлю ссылку!
7. Хочешь видеть больше такого контента? Обязательно подпишись!
8. Хочешь такие же результаты? Напиши мне «X» для записи на индивидуальную консультацию!
9. Поделись этим с лучшим другом/мамой/партнером по гольфу!
10. Если полезно - подпишись. Я публикую такие материалы каждый день!
11. Хочешь больше информации? Нажми на мое выделенное (название highlights)!
12. Ссылка в профиле, переходи!
13. Подробности в хайлтайтсах/шапке профиля! И не забудь подписаться!

##Шаг4
Переведи caption_original на {language} язык. 

#Specifics
- выполняй строго по шагам. Ничего не пропускай
- Все пиши на {language} языке

#OUTPUT
hook = [hook1, hook2, hook3, hook4, hook5]
content = content_translated
cta = [cta1, cta2, cta3]
caption = caption_translated
'''

json_schema = {
    "name": "video_transcription",
    "strict": true,
    "schema": {
        "type": "object",
        "properties": {
            "hook": {
                "type": "array",
                "description":
                "A list of hooks generated for the video based on the transcription.",
                "items": {
                    "type": "string"
                }
            },
            "content": {
                "type": "string",
                "description": "The translated content from the original."
            },
            "cta": {
                "type": "array",
                "description":
                "A list of call-to-action phrases generated for the video.",
                "items": {
                    "type": "string"
                }
            }
        },
        "required": ["hook", "content", "cta"],
        "additionalProperties": false
    }
}
